version: '3.8'

services:
  api:
    build: ./api
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=${MONGO_URL}
    networks:
      - app_network
    env_file:
      - .env

  bot:
    build: ./bot
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=${MONGO_URL}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    networks:
      - app_network
    env_file:
      - .env

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - app_network

  mongodb:
    image: mongo:4.4
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

networks:
  app_network:

volumes:
  mongodb_data:
