version: '3.8'

services:
  api:
    build: ./api
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017
    networks:
      - app_network

  bot:
    build: ./bot
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - TELEGRAM_BOT_TOKEN=7201805915:AAHose5a0zVs-bs98WwcV00MRWCmcz66_p0
    networks:
      - app_network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - app_network

  mongodb:
    image: mongo:4.4
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

networks:
  app_network:

volumes:
  mongodb_data:
